### ISSUE TITLE
Trigger Discovery enhancements to support discovery of selected features.

### ISSUE THREAD

**Issue by kamalkrbh** [STORDIS/orca_nw_lib#105]
Enhance trigger_discovery function so that it can -
-  Discover all the features if no feature is provided.
-  Should discover the list of features if provided.

All the test cases of orca_backend and orca_nw_lib should be passing after the implementation.

**Comment by ramya6737** [comment]
All test cases for orca_backend and orca_nw_lib are passing successfully after the implementation of the enhanced trigger_discovery function.

**Comment by kamalkrbh** [comment]
@ramya6737 , Is there any PR ?

**Comment by ramya6737** [comment]
Yes Kamal, I have linked the PR for the changes.
