### ISSUE TITLE
device and interface discovery enhancements.

### ISSUE THREAD

**Issue by kamalkrbh** [STORDIS/orca_nw_lib#106]
Insert device and interface data into prometheus after discovery.
With a check based on the property "telemetry_db" defined in orca_nw_lib.yml,  In the discovery functions of device and interface insert data into prometheus as well.

A utility file prometheus_db_util.py should be created for prometheus connection management and feature specific modules like device_promdb.py and interface_promdb.py will have the feature specific prometheus db interactions.

All the test cases of orca_backend and orca_nw_lib should be passing after the implementation.

**Comment by ramya6737** [comment]
PR for this task: https://github.com/STORDIS/orca_nw_lib/pull/118
