### ISSUE TITLE
System Metric Support.

### ISSUE THREAD

**Issue by kamalkrbh** [STORDIS/orca_nw_lib#114]
A list of yang models supported by SONiC devices can be found at https://<switch_ip>/ui
System Metrics can be found at yang model - openconfig-system:system

Inside yang model - openconfig-system:system

Following metrics should be supported.

###  DNS
Path - https://10.10.229.88/restconf/data/openconfig-system:system/dns/servers/server
Sample output -
``` json
{
  "openconfig-system:server": [
    {
      "address": "10.10.231.254",
      "state": {
        "address": "10.10.231.254",
        "address-type": "DYNAMIC"
      }
    }
  ]
} 
```

### Event
Path - https://10.10.229.88/restconf/data/openconfig-system:system/openconfig-events:events/event
Sample output -
``` json
{
  "openconfig-events:event": [
    {
      "id": "9",
      "state": {
        "id": "9",
        "resource": "system_status",
        "severity": "INFORMATIONAL",
        "text": "System is ready",
        "time-created": "1730807070331648256",
        "type-id": "SYSTEM_STATUS"
      }
    }
]
}
```
only the json for key "state" needs to be saved in prometheus.

### Uptime
Path - https://10.10.229.88/restconf/data/openconfig-system:system/openconfig-system-ext:infra/state
Sample output -
``` json
{
  "openconfig-system-ext:state": {
    "reboot-cause": "\nUnknown",
    "show-user-list": [
      ""
    ],
    "uptime": "0 days, 5 hours, 25 minutes"
  }
}
```
### memory
Path - https://10.10.229.88/restconf/data/openconfig-system:system/memory/state
Sample output -
``` json
{
  "openconfig-system:state": {
    "buff-cache": "1216016",
    "physical": "3697408",
    "reserved": "1900608",
    "unused": "580784"
  }
}
```
### NTP
Path - https://10.10.229.88/restconf/data/openconfig-system:system/ntp/servers/server
Sample output -
``` json
{
  "openconfig-system:server": [
    {
      "address": "10.10.231.254",
      "state": {
        "address": "10.10.231.254",
        "now": 26,
        "peer-delay": "1559",
        "peer-jitter": "13020",
        "peer-offset": "502",
        "peer-type": "u",
        "poll-interval": 512,
        "reach": "377",
        "refid": "185.197.135.21",
        "sel-mode": "*",
        "stratum": 3
      }
    }
  ]
} 
```

- Relevant Grafan panels should be created.
- Subscription should be preferred if supported by path otherwise perform get operations. ***___Note___*** - If no subscription is supported then while doing gnmi get we can send multiple paths in single request.
- Data should be saved in prometheus and in influxdb. 
- All test cases of ORCA should be passing after delivery.

**Comment by Parth-Kakadia** [comment]
![Image](https://github.com/user-attachments/assets/b1c7e59e-86d7-4eab-8db1-ea6805132354)
![Image](https://github.com/user-attachments/assets/82e9054b-b0da-4bfd-a3be-7a0d637b361b)
