### ISSUE TITLE
Platform Metric Support

### ISSUE THREAD

**Issue by kamalkrbh** [STORDIS/orca_nw_lib#115]
A list of yang models supported by SONiC devices can be found at https://<switch_ip>/ui
Switch platform information like fans, psu and temperature sensirs are available in yang model sonic-platform:sonic-platform

All info is available at single path - https://10.10.131.111/restconf/data/sonic-platform:sonic-platform

- Relevant Grafan panels should be created. e.g. The basic info about fan and temperature sensors can be shown in tabular format but some grphical formats about temperature and fan speeds should also be shown as in Monsoon1.
- Data should be saved in prometheus and in influxdb. 
- Subscription should be preferred if supported by path otherwise perform get operations.
- All test cases of ORCA should be passing after delivery.

**Comment by ramya6737** [comment]
PR: https://github.com/STORDIS/orca_nw_lib/pull/128
On Hold

**Comment by ramya6737** [comment]
InfluxDB Dashboard Json: [Monsoon2.0_Influxdb-1733757291427.json](https://github.com/user-attachments/files/18080015/Monsoon2.0_Influxdb-1733757291427.json)

**Comment by ramya6737** [comment]
Already uploaded the InfluxDB Dashboard JSON in Monsoon 2.0 for Platform

**Comment by kamalkrbh** [comment]
@ramya6737 , A lots of files has been deleted, please do a proper merge with main branch first.
