### ISSUE TITLE
MCLAG Metrics

### ISSUE THREAD

**Issue by kamalkrbh** [STORDIS/orca_nw_lib#119]
Path: /restconf/data/openconfig-mclag:mclag

Sample Output: 
{
  "openconfig-mclag:mclag": {
    "mclag-domains": {
      "mclag-domain": [
        {
          "domain-id": 0,
          "config": {
            "domain-id": 0,
            "source-address": "string",
            "peer-address": "string",
            "session-vrf": "string",
            "peer-link": "string",
            "mclag-system-mac": "string",
            "keepalive-interval": 0,
            "session-timeout": 0,
            "delay-restore": 0
          },
          "state": {
            "domain-id": 0,
            "source-address": "string",
            "peer-address": "string",
            "session-vrf": "string",
            "peer-link": "string",
            "mclag-system-mac": "string",
            "keepalive-interval": 0,
            "session-timeout": 0,
            "delay-restore": 0,
            "oper-status": "OPER_UP",
            "role": "ROLE_ACTIVE",
            "system-mac": "string",
            "delay-restore-start-time": "string"
          }
        }
      ]
    },
    "interfaces": {
      "interface": [
        {
          "name": "string",
          "config": {
            "name": "string",
            "mclag-domain-id": 0,
            "mclag-id": 0
          },
          "state": {
            "name": "string",
            "mclag-domain-id": 0,
            "mclag-id": 0,
            "local": {
              "traffic-disable": true,
              "port-isolate": true,
              "oper-status": "OPER_DOWN"
            },
            "remote": {
              "oper-status": "OPER_UNKNOWN"
            }
          }
        }
      ]
    },
    "vlan-interfaces": {
      "vlan-interface": [
        {
          "name": "string",
          "config": {
            "name": "string",
            "unique-ip-enable": "ENABLE"
          },
          "state": {
            "name": "string",
            "unique-ip-enable": "ENABLE"
          }
        }
      ]
    },
    "mclag-gateway-macs": {
      "mclag-gateway-mac": [
        {
          "gateway-mac": "string",
          "config": {
            "gateway-mac": "string"
          },
          "state": {
            "gateway-mac": "string"
          }
        }
      ]
    },
    "vlan-ifs": {
      "vlan-if": [
        {
          "name": "string",
          "config": {
            "name": "string",
            "peer-gateway-enable": "ENABLE"
          },
          "state": {
            "name": "string",
            "peer-gateway-enable": "ENABLE"
          }
        }
      ]
    }
  }
}

**Comment by ramya6737** [comment]
PR for this task: https://github.com/STORDIS/orca_nw_lib/pull/120

**Comment by kamalkrbh** [comment]
@ramya6737 , Is grafana dashboard also created ?

**Comment by ramya6737** [comment]
Since there is no data for MCLAG, Grafana is displaying 'No Data.'

**Comment by ramya6737** [comment]
On hold

**Comment by ramya6737** [comment]
InfluxDB Dashboard Json: [Monsoon2.0_Influxdb-1733757291427.json](https://github.com/user-attachments/files/18079988/Monsoon2.0_Influxdb-1733757291427.json)

**Comment by kamalkrbh** [comment]
@ramya6737 , Jsons should be part of Monsoon2 code. Create a PR in Monsoon2 as well with those JSONs.

**Comment by ramya6737** [comment]
Completed InflluxDB And Prometheus Dashboards and updated in Monsoon2 PR: https://github.com/STORDIS/monsoon2/pull/20

**Comment by kamalkrbh** [comment]
MCLAG ,Test cases are failing.
