### ISSUE TITLE
CRM Metrics

### ISSUE THREAD

**Issue by Parth-Kakadia** [STORDIS/orca_nw_lib#124]
### CRM
Path- sonic-system-crm:sonic-system-crm/CRM/CRM_LIST

**Comment by kamalkrbh** [comment]
@Parth-Kakadia , Please refer path - https://10.10.131.111/restconf/data/openconfig-system:system/openconfig-system-crm:crm

**Comment by Parth-Kakadia** [comment]
![Image](https://github.com/user-attachments/assets/8ddd83d3-74a5-4b8c-bbc2-10bafd426845)
