### ISSUE TITLE
SAG Metrics

### ISSUE THREAD

**Issue by kamalkrbh** [STORDIS/orca_nw_lib#125]

**Comment by ramya6737** [comment]
PR link: https://github.com/STORDIS/orca_nw_lib/pull/129
On hold

**Comment by ramya6737** [comment]
InfluxDB Dashboard Json: [Monsoon2.0_Influxdb-1733757291427.json](https://github.com/user-attachments/files/18080006/Monsoon2.0_Influxdb-1733757291427.json)

**Comment by kamalkrbh** [comment]
@ramya6737 , Jsons should be part of Monsoon2 code. Create a PR in Monsoon2 as well with those JSONs.

**Comment by ramya6737** [comment]
Completed InflluxDB And Prometheus Dashboards and updated in Monsoon2 PR: https://github.com/STORDIS/monsoon2/pull/20
