### ISSUE TITLE
Perform a system ready check before doing operations on device.

### ISSUE THREAD

**Issue by kamalkrbh** [STORDIS/orca_nw_lib#47]
- [x] Provide an API to get the current system status.

- [x] Keep system state up2date as a separate property in the Device node in Neo4j . Use gNMI subscriptions to keep the DB updated.
 Path - /restconf/data/openconfig-system:system/openconfig-events:events/event can be subscribed, Here a list of system event can be found, look for the latest event with "resource": "system_status" and check the text to determine system status. Although the list of event can also be used to show operational logs in the UI.

"state": {
        "id": "10",
        "resource": "system_status",
        "severity": "INFORMATIONAL",
        "text": "System is not ready - one or more services are not up",
        "time-created": "1716825704836528384",
        "type-id": "SYSTEM_STATUS"
      }

- [x] In orca_nw_lib Before executing any device operations (in xyz_gnmi.py) should first check if system is ready (from database not from device, a timeout retry mechanism should be implemented) if not exception should be raised with clear message in the exception.

During the discovery of device as there is no node present in the DB to store the property, Simply do a get with timeout and retry on the above path to know system status before triggering the discovery.

**Comment by rahul-1475** [comment]
- Test case to check to subscrition sync for all subscribed apis.

**Comment by rahul-1475** [comment]
orca_backend pr: https://github.com/STORDIS/orca_backend/pull/73
orca_nw_lib pr: https://github.com/STORDIS/orca_nw_lib/pull/96
