### ISSUE TITLE
Update path for Port Channel configuration.

### ISSUE THREAD

**Issue by kamalkrbh** [STORDIS/orca_nw_lib#48]
In SONiC 4.2.0,

Using the path 

https://{device_ip_list[0]}/restconf/data/sonic-portchannel:sonic-portchannel/PORTCHANNEL_MEMBER/PORTCHANNEL_MEMBER_LIST
with the payload 

req_body = {
"sonic-portchannel:PORTCHANNEL_MEMBER_LIST": [
{"name": "PortChannel101", "ifname": "Ethernet56"},
{"name": "PortChannel101", "ifname": "Ethernet76"},
]
}
It responds with 204 Http code. but only one member is added at the end.
On further analysis, while adding portchannel member via CLI, I see that one of the interfaces is a VLAN member and can't be added to the PortChannel.
REST or gNMI call should also fail in such case but they show a incorrect successful status.

**Comment by kamalkrbh** [comment]
Use the correct path recorded in log file.

**Comment by rahul-1475** [comment]
- Using the above path to add members to the port channel successfully added both members.

- For adding VLAN members, we are currently using the exact path that was used in the CLI 
 i.e., https://10.10.229.58/restconf/data/openconfig-interfaces:interfaces/interface={port_channel_name}/openconfig-if-aggregate:aggregation/openconfig-vlan:switched-vlan/config.

- Updating the access VLAN is not reflected and cannot be changed to a new VLAN ID.

- More information is needed on this task.

**Comment by kamalkrbh** [comment]
@rahul-1475 
Port channel notebook has been updated with the following cells.
Add/Remove/Get Trunk Member VLAN
Add/Remove/Get Access Member VLAN
Please refer.

**Comment by rahul-1475** [comment]
orca_backend pr: https://github.com/STORDIS/orca_backend/pull/54
orca_nw_lib pr: https://github.com/STORDIS/orca_nw_lib/pull/85

**Comment by kamalkrbh** [comment]
@rahul-1475 , Some chages are requested on the PRs for backend.
