### ISSUE TITLE
Advance config options for PortChannels.

### ISSUE THREAD

**Issue by kamalkrbh** [STORDIS/orca_nw_lib#52]
Following Additional parameters needed to be supported for portchannels - 

- [x] Add property “static” (configurable)
- [x] fallback (configurable) default false.
- [x] fast-rate (configurable) default false.
- [x] min-links (configurable) possible values 1-32 default 1.
- [x] description (configurable) default false.
- [x] graceful_shutdown_mode (configurable) default ENABLE
- [x] Add member vlan to portchannel. (Currently only Ethernets can be PortChannel members)
- [x] Assign/Remove IP to portchannel. (IP validation to be performed on UI and backend)
- [x] Tests for config verification of above parameters.
- [x] UI - Respective Display and Config Operations need to be supported on UI.  The "name" field on the UI is respective to "static" field above in the backend. On the UI "name" field can be renamed to "protocol name" and if value of "static" is true the "protocol name" should be "lacp" else "protocol name" should be "none".

For more details on payloads and openconfig paths refer PortChannel.ipynb in SONiCPlayer.
Cells - "Config Port Channel", "Assign/Get/Delete IP from Portchannel"

**Comment by kamalkrbh** [comment]
Vivek started the UI part.

**Comment by vivek-metricdust** [comment]
Issues found in backend

1. the backedn will prompt the error i.e, - Couldn't discover Port Channel on device 10.10.229.58, Reason: invalid literal for int() with base 10: '2-4'
2. sometimes the response is just the trunk vlans only
