### ISSUE TITLE
STP Configuration in ORCA (New Tab)

### ISSUE THREAD

**Issue by kamalkrbh** [STORDIS/orca_nw_lib#57]
STP (Spanning Tree Protocol) Configuration -

- [x] STP Global Config - Payload and path are defined in SONiC Player Cell - "GET/SET/DELETE STP Global Config"
- Global STP config will be a new node in DB, so a new model created with the properties received as GET operation at the path described in above cell.
- The new node stp will have a "HAS" relation with its Device node in the DB. 
- A respective stp.py stp_db.py stp_gnmi.py needs to be created, Also discovery of STP global mechanism needed to be integrated in discovery.py
- orca_backend should provide CRUD rest endpoints for above.
- test cases covering operations on all the parameters.

- [x] Update DB - for the changes done in STP global config after its discovery. The path in the cell of the SONiC Player described above can be subscribed to receive ON_CHANGE notifications only.

**Comment by rahul-1475** [comment]
PR links:

- orca_nw_lib: https://github.com/STORDIS/orca_backend/pull/51
- orca_backend: https://github.com/STORDIS/orca_nw_lib/pull/80
