### ISSUE TITLE
Configure MCLAG Ports

### ISSUE THREAD

**Issue by kamalkrbh** [STORDIS/orca_nw_lib#65]
- [x] Configuration of MCLAG ports, Respective cells in SONiC Player notebook are 
- Get MCLAG Interface
- Config MCLAG Ports
- Delete MCLAG Ports
- [x] Test cases to validate the above configuration.
- [x] Respectively UI needs to be updated.

**Comment by rahul-1475** [comment]
- MCLAG configuration for port channel already exists.
- Tried adding Ethernet ports to the MCLAG is throwing an error with the message: "Invalid PortChannel name pattern".
- Test cases for mclag port channel memebrs already exits.
- UI task will be assigned to @vivek-metricdust

**Comment by vivek-metricdust** [comment]
issue found in backend
1. The get api for mclag is giving all port channel data (mclag_members) which can be reduced to only lag_name
2. The get request needs domain id to give the members and if domain id is not provided its not giving members data which must be handled in backend.

**Comment by vivek-metricdust** [comment]
Issue found:
Currently the deletion of members is not supported for a particular member if deletion api is triggered it is deleting all the members (from members of mclag) 
Instead, we need to support the deletion of particular member / members

**Comment by vivek-metricdust** [comment]
Issue found:
Currently the deletion of members is not supported for a particular member if deletion api is triggered it is deleting all the members (from members of mclag)
Instead, we need to support the deletion of particular member / members

**Comment by vivek-metricdust** [comment]
PR's for issue has been created

- [Configure mclag ports - lib - #65 #78](https://github.com/STORDIS/orca_nw_lib/pull/78)
- [Configure mclag ports - b - #65 STORDIS/orca_backend#49](https://github.com/STORDIS/orca_backend/pull/49)
- [Configure mclag ports #65 STORDIS/orca_ui#138](https://github.com/STORDIS/orca_ui/pull/138)

Also, its better to merge and close the [#63](https://github.com/STORDIS/orca_nw_lib/issues/63) Issue before merging and closing this

**Comment by kamalkrbh** [comment]
Review comments provided, moving to "change requested".
