### ISSUE TITLE
Port-Group speed updates and Interface valid-speeds issue.

### ISSUE THREAD

**Issue by kamalkrbh** [STORDIS/orca_nw_lib#67]
If port group speed is set to 25G , all interface in the port-group are updated to have the speed 25G, but the valid speeds and adv-speed set is still 1G and 10G which is not correct.

- [x] The correct behaviour would be if port-group speed is updated, after receving the port-group update via gNMI subscription make an additional gnmi get to update the valid_speeds field for interface at sonic-port:sonic-port/PORT/PORT_LIST={interface_name}.
- [x] Write test case for above.

**Comment by kamalkrbh** [comment]
@rahul-1475 , Perhaps discovering the Ethernets in the port groups might be an easy solution.

**Comment by rahul-1475** [comment]
pull request links:

- https://github.com/STORDIS/orca_backend/pull/42
- https://github.com/STORDIS/orca_nw_lib/pull/71

**Comment by kamalkrbh** [comment]
@rahul-1475  , Requested changes . Moving it to In Progress.

**Comment by kamalkrbh** [comment]
Moving to "Changes Requested Post Review" for better tracking.

**Comment by kamalkrbh** [comment]
@rahul-1475 , There are merge conflicts in both the PRs.
