### ISSUE TITLE
Interface breakout configuration support.

### ISSUE THREAD

**Issue by kamalkrbh** [STORDIS/orca_nw_lib#72]

**Comment by rahul-1475** [comment]
orca_backend pr: https://github.com/STORDIS/orca_backend/pull/63
orca_nw_lib pr: https://github.com/STORDIS/orca_nw_lib/pull/90

**Comment by kamalkrbh** [comment]
@rahul-1475 ,
A normal ethernet and a broken ethernet should have the same db model and both type of Ethernet has the “HAS” relationship with device, But once an ethernet is broken the already existing Ethernet should be updated in the DB and additionally the brokenout Ethernet should be discovered and added to DB.
 
For example - If Ethernet48 is broken into 4x10G config then Ethernet48 should remain in DB and should be updated with its new properties i.e. its alias would change like Eth1/49/1 , Its lanes which were like 121,122,123,124 earlier, but after breakout to be updated to just single lane i.e. 121.

Adiitionally the new interfaces Ethernet49, Ethernet50, Ethernet51 should be discovered as new interfaces (similar to other Ethernets) with all relevant properties as above.

New properties to be added to the existing Interface model -
breakout_mode_supported - True/False. With the number of lanes we can determine if the Ethernet supports breakout or not, single lane means breakout isn’t supported otherwise yes it is.
breakout_mode - current break out mode confgured (property should be visible on master and all other broken ports)
break_out status - current status of breakout


Also there should be a check that already broken ports must not be broken further i.e. may be the alias Eth1/49/1 can be determined if its a broken out port.
Also while deleting a breakout mode the master ethernet should be updated (rediscoverred or check for subscription) with its properties i.e. alias should be now Eth1/49 , should have all 4 lanes assigned to it and any other property update. and other broken out port should be removed from DB.


gNMI subscription should be used if supported first to update the DB.

Test cases to test every above functionality.

**Comment by vivek-metricdust** [comment]
issue found:

- portchannel is not getting created when the PUT api is called and its getting created in the 2 PUT api call
- while deleting portchannel 1st delete api call will give 200 but still we can see it in list and 2nd delete api call will remove it from list but results in No resource found in responce

**Comment by rahul-1475** [comment]
- added new test case to check breakout supported on discovery.
- test case failures for adding and deleting in portchannel can be referred at issue 
 https://github.com/STORDIS/orca_backend/issues/67

**Comment by kamalkrbh** [comment]
Merged PRs , Still waiting for UI PR.
