### ISSUE TITLE
Subinterface nodes remains in DB even after deleting all the devices from ORCA.

### ISSUE THREAD

**Issue by kamalkrbh** [STORDIS/orca_nw_lib#83]
Subinterface nodes remains in neo4j db even after all the devices from ORCA has been deleted. Neo4j is not cleaned properly.
Also , Any gRPC stubs and subcriptios should also be cleaned after a device is removed from ORCA.

**Comment by rahul-1475** [comment]
orca_nw_lib pr: https://github.com/STORDIS/orca_nw_lib/pull/131

**Comment by rahul-1475** [comment]
#133  is also fixed in this pr.
