### ISSUE TITLE
Delete Subscription - Failed to remove subscirption on delete device

### ISSUE THREAD

**Issue by rahul-1475** [STORDIS/orca_nw_lib#95]
Subscription is remove is failed on device delete.

- On device removal stub channel can be closed. Which will eventually kill the subscription thread
- In test cases tear down also the stub channel can be closed.
- There can still remain a method which will remove only the subscription thread not the entire channel.

**Comment by rahul-1475** [comment]
orca_nw_lib pr :- https://github.com/STORDIS/orca_nw_lib/pull/101
orca_backend :- https://github.com/STORDIS/orca_backend/pull/81

**Comment by kamalkrbh** [comment]
@rahul-1475 , Anything remains here ?

**Comment by kamalkrbh** [comment]
The stream being cancelled is a new object not which is is receiving the notifications.
